export const MONTHS_NAMES = {
    es: ["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"],
    en: ["JANUARY", "FENRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"]
}

export const WEEKDAYS = {
    es: ["DOMINGO", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO"],
    en: ["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THUERSDAY", "FRIDAY", "SATURDAY"]
}   